sudo: required
services:
  - docker

before_install:
  - docker build -t andreitam/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true andreitam/react-test npm test

after_success:
  - docker build -t andreitam/multi_client ./client
  - docker build -t andreitam/multi_nginx ./nginx
  - docker build -t andreitam/multi_server ./server
  - docker build -t andreitam/multi_worker ./worker
  #Login to Docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Push images to docker hub
  - docker push andreitam/multi_client
  - docker push andreitam/multi_nginx
  - docker push andreitam/multi_server
  - docker push andreitam/multi_worker
